/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://l462mij5cfcv3e3nhxs3lm6c7y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-blu5iwom6vamjl6fosil7knzqe",
    "aws_cognito_identity_pool_id": "us-east-1:ba57e14d-c4b0-46b2-bb15-280b4c0a10c0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_V1qNN6gEt",
    "aws_user_pools_web_client_id": "5hemnvvl7b071rbh6ferpdt9s7",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "logbucket71500-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
